"""empty message

Revision ID: 3f5ff933e4f0
Revises: 674d259c8d3a
Create Date: 2020-05-26 07:25:53.625010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5ff933e4f0'
down_revision = '674d259c8d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('ocr', sa.String(length=480), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'ocr')
    # ### end Alembic commands ###
