"""empty message

Revision ID: 7db8dc9cdfd7
Revises: 3f5ff933e4f0
Create Date: 2020-05-26 09:35:08.040254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db8dc9cdfd7'
down_revision = '3f5ff933e4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'created_date')
    # ### end Alembic commands ###
