"""empty message

Revision ID: f72d08b97572
Revises: 029be9f9b861
Create Date: 2020-05-08 21:07:44.237337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f72d08b97572'
down_revision = '029be9f9b861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
